version: "3.7"

services:
  # image project
  app:
    container_name: laravel
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    stdin_open: true
    tty: true
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - laravel

  # nginx
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8989:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel

  # queue
  queue:
    container_name: queue
    image: especializati/laravel-app
    restart: unless-stopped
    command: "php artisan queue:work"
    volumes:
      - ./:/var/www
    depends_on:
      - redis
      - app
    networks:
      - laravel

  # redis
  redis:
    container_name: redis
    image: redis:latest
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
